# Site
repository: SeungyeonHwang/SeungyeonHwang.github.io

# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: ãƒ•ã‚¡ãƒ³(Hwang Seungyeon)
title: Webç³»ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢
email: syhwang.web@gmail.com
phone: 

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  SeungyeonHwang
linkedin_username: seungyeon-hwang-09a722182

# Additional icon links
# additional_links:
# - title: 
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# About Me Section
about_profile_image: images/profile.jpeg
about_title: ğŸ”– åŸºæœ¬æƒ…å ±
about_content: |
  |é …ç›®|å†…å®¹|
  |----|----|
  |åå‰|ãƒ•ã‚¡ãƒ³ ã‚¹ãƒ³ãƒ¨ãƒ³|
  |å±…ä½åœ°|æ±äº¬éƒ½ ä¸‰é·¹å¸‚(éŸ“å›½å‡ºèº«)|
  |ãƒãƒ¼ãƒˆãƒ•ã‚©ãƒªã‚ª|[SeungyeonHwang](https://github.com/SeungyeonHwang)|
  |å­¦æ­´|å¤§å­¦å’|
  |è³‡æ ¼|ã‚ªãƒ©ã‚¯ãƒ«èªå®šJavaãƒ—ãƒ­ã‚°ãƒ©ãƒãƒ¼(Silver),<br/>æƒ…å ±å‡¦ç†æŠ€å¸«(å¿œç”¨æƒ…å ±æŠ€è¡“è€…ç›¸å½“)|
  |è‹±èªåŠ›|TOEIC845ç‚¹åŠã‚¢ãƒ¡ãƒªã‚«ç•™å­¦çµŒé¨“æœ‰ã‚Š|

# Activity Section
activity_title: ğŸ“Œ æ¦‚è¦
activity_content: |
  ## â—¼ï¸è‡ªå·±ç´¹ä»‹
  > åˆã‚ã¾ã—ã¦ã€‚ğŸ™‡â€â™‚ï¸  
    è‡ªåˆ†ãŒå¼·ãå…±æ„Ÿã§ãã‚‹ã‚µãƒ¼ãƒ“ã‚¹ã‚’å‡ºä¼šã£ã¦ä¸–ã®ä¸­ã«åºƒã’ã¦è¡ŒããŸã„ã¨ã„ã†ç›®æ¨™ã‚’æŒã£ã¦ã„ã‚‹ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢`ãƒ•ã‚¡ãƒ³`ã¨ç”³ã—ã¾ã™ã€‚  
  > `2020å¹´2æœˆ`ã‹ã‚‰æ ªå¼ä¼šç¤¾ãƒ›ãƒ¼ãƒ—ã‚¹ã¨ã„ã†ã‚·ã‚¹ãƒ†ãƒ é–‹ç™ºä¼šç¤¾ã§ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã¨ã—ã¦æºã‚ã£ã¦ã„ã¾ã™ã€‚  
    å…¥ç¤¾å¾Œã€`åŸºå¹¹ã‚·ã‚¹ãƒ†ãƒ ã®æ§‹ç¯‰`ï¼ˆä¸»ã«ERPã‚·ã‚¹ãƒ†ãƒ ï¼‰ã«å¾“äº‹ã—ã€è¦ä»¶å®šç¾©ã‚„è¨­è¨ˆãªã©ã®ä¸Šæµå·¥ç¨‹ã‹ã‚‰ã€  
    `ã‚¢ã‚¸ãƒ£ã‚¤ãƒ«`é–‹ç™º(ã‚¹ã‚¯ãƒ©ãƒ )ã§APIé–‹ç™ºã‚„ãƒ†ã‚¹ãƒˆã‚³ãƒ¼ãƒ‰ä½œæˆã¾ã§çµŒé¨“ã—ã¦ãŠã‚Šã¾ã—ãŸã€‚  
  <br>  

  ## â—¼ï¸é–‹ç™ºæ¥­å‹™ã«ã¤ã„ã¦..  
  > é–‹ç™ºã«é–¢ã—ã¦ã¯`Java`è¨€èªã‚’ç”¨ã„ãŸå—ç™ºæ³¨ã‚·ã‚¹ãƒ†ãƒ ã®ã‚¹ã‚¯ãƒ©ãƒƒãƒé–‹ç™ºã§  
  `ã‚µãƒ¼ãƒã‚µã‚¤ãƒ‰ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢`ã¨ã—ã¦`æ©Ÿèƒ½å…·ç¾åŒ–(APIé–‹ç™º)`åŠã³`ãƒ†ã‚¹ãƒˆã‚³ãƒ¼ãƒ‰ä½œæˆ`ã‚’æ‹…å½“ã—ã¦ã¾ã—ãŸã€‚  
  > Webã§æä¾›ã—ã¦ã„ã‚‹æ§˜ã€…ã®ã‚µãƒ¼ãƒ“ã‚¹ã«éå¸¸ã«èˆˆå‘³æ·±ã„ã§ã™ã€‚  
  > ã¾ãŸçŸ¥ã‚‰ãªã„ã“ã¨ã‚’èª¿ã¹ãŸã‚Šå‹‰å¼·ã™ã‚‹ã®ãŒå¥½ãã§ã™ã®ã§`æ‰‹ã‚’å‹•ã‹ã›ã‚‹ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢`ã¨ã—ã¦è²¢çŒ®ã§ãã‚‹äººæã«ãªã‚ŠãŸã„ã¨ã„ã†æƒ³ã„ã‚’æŒã£ã¦è‡ªä¸»å‹‰å¼·ã—ã¦ã„ã¾ã™ã€‚  
  > ç‰©ã¥ãã‚ŠãŒå¥½ããªæ€§æ ¼ã‚’æ´»ã‹ã—ã¦ãƒ—ãƒ­ãƒ€ã‚¯ãƒˆé€ ã‚Šã«è²¢çŒ®ã—ãŸã„ã§ã™ã€‚  

# Skill Section
skill_title: ğŸ’» ã‚¹ã‚­ãƒ«
skill_content: |
  **å®Ÿæ¥­å‹™ã§ä½¿ç”¨ã—ãŸæŠ€è¡“ã¯`ã‚·ãƒ³ã‚¿ãƒƒã‚¯ã‚¹ãƒã‚¤ãƒ©ã‚¤ãƒˆ`ã§è¡¨ç¤ºã—ã¾ã™ã€‚**  
  <br>

  ## **â—¼ï¸ è¨€èª**  
  `Java` | `Groovy` | `SQL` | Python | JavaScript | HTML | CSS | JSP | Ruby   
  <br>
  
  ## **â—¼ï¸ ãƒ•ãƒ¬ãƒ¼ãƒ ãƒ¯ãƒ¼ã‚¯ç­‰**  
  `Micronaut` | `Spock` | `Querydsl` | Spring | Ruby on Rails | jQuery   
  <br>
  
  ## **â—¼ï¸ ãã®ä»–**  
  `Git` | `GitHub & Lab` | `Docker` | Apache | Tomcat | AWS   
  <br>
  
  ## **â—¼ï¸ ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹**  
  `PostgreSQL` | MySQL | Oracle
# OpenSource Section
open-source_title: âœ¨ ã‚­ãƒ£ãƒªã‚¢ãƒ—ãƒ©  
open-source_content: |
  
  ## â—¼ï¸è‡ªåˆ†ãŒè€ƒãˆã¦ã„ã‚‹ã‚­ãƒ£ãƒªã‚¢ãƒ—ãƒ©ãƒ³ã¨ã—ã¦ã¯`ã‚µãƒ¼ãƒ“ã‚¹å¿—å‘ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢`ã«ãªã‚ã†ã¨ã„ã†ã“ã¨ã§ã™ã€‚  
  <br>  

  ## â‘  åˆã‚ã®æ–¹ã¯ã‚¬ãƒªã‚¬ãƒªã¨ã‚³ãƒ¼ãƒ‰ã‚’æ›¸ããƒ—ãƒ¬ã‚¤ã‚¢ã¨ã—ã¦æ´»èºã—ã¦è¡ŒããŸã„ã§ã™ã€‚   
    - ç¤¾å†…ã§çµŒé¨“ã‚’ç©ã¿ã€è‰²ã€…ã®æ©Ÿèƒ½ã‚’å®Ÿè£…ã—ã¦ã‚¿ãƒ¼ã‚²ãƒƒãƒˆã«ãªã‚‹ãƒ¦ãƒ¼ã‚¶ãƒ¼ã®å±æ€§ã‚’æ‹¡å¤§ã—ã¦ã•ã‚‰ã«ã‚µãƒ¼ãƒ“ã‚¹ã‚’å±•é–‹ã—ã¦ã„ããŸã„ã§ã™ã€‚  
    <br>  

  ## â‘¡ å¾ŒåŠã®æ–¹ã§ã¯ãƒ‡ã‚£ãƒ¬ã‚¯ã‚¿ãƒ¼ã«ãªã£ã¦ã¿ãŸã„ã§ã™ã€‚  
    - ä¼šç¤¾ãŒã‚„ã£ã¦ã„ã‚‹äº‹æ¥­ã®ä¸­ã€ã‚‚ã—Globalã«å±•é–‹ã—ãŸã„ã‚‚ã®ãŒã‚ã‚Œã°é–‹ç™ºã‚¹ã‚­ãƒ«ä»¥å¤–ã«ã‚‚ã‚¢ãƒ¡ãƒªã‚«ã§ã®çµŒé¨“ã¨ã‹ç§ãŒéŸ“å›½äººã§ã‚ã‚‹ã¨ã„ã†ç‚¹ã‚’æ´»ã‹ã—ã¦è²¢çŒ®ã§ãã‚‹ã¨ã“ã‚ãŒã‚ã‚Œã°å¬‰ã—ã„ã¨æ€ã„ã¾ã™ã€‚  

# Experience Section
experience_title: ğŸ“‘ ä¸»ãªæ¥­å‹™çµŒæ­´ 

# Projects Section
projects_title: ğŸ’¡ ãƒãƒ¼ãƒˆãƒ•ã‚©ãƒªã‚ª

# Education Section
# education_title: ä¸»ãªæ¥­å‹™çµŒæ­´ 



# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]


